[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/mercadolibre/callback"
  to = "/.netlify/functions/mercadolibre-callback"
  status = 200

[[redirects]]
  from = "/api/mercadolibre/notificaciones"
  to = "/.netlify/functions/mercadolibre-notificaciones"
  status = 200
